# deployment config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  # number of pods we want to create
  replicas: 1
  # find all pods that have label app event-bus
  selector:
    matchLabels:
      # app doesn't have any special meaning it could be any word
      app: event-bus
  # apply this config to the pods
  template:
    metadata:
      # we want pods to have label app: event-bus
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: ivanmitkov/event-bus:latest
# after change config kubectl apply -f [config file name]
#create multiple objects in one file
---
#configuration for Cluster IP service
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  selector:
    app: event-bus
  #optional default is ClusterIP
  type: ClusterIP
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005
